apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-api
  template:
    metadata:
      labels:
        app: aks-api
    spec:
      containers:
      - name: aks-api
        image: aksdevopsacrjdm0521.azurecr.io/aks-api:latest
        ports:
        - containerPort: 8000