apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "66ac2951-0195-471e-83db-ec2431ef16f3"
    keyvaultName: "kv-jdm0521-devops"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
    tenantId: "28f9d355-136c-48d5-a6ca-397aa9104618"