name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: aksdevopsacrjdm0521
  RESOURCE_GROUP: rg-aks-devops
  AKS_CLUSTER: aks-devops-cluster
  IMAGE_NAME: aks-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      run: |
        az aks get-credentials \
          --name $AKS_CLUSTER \
          --resource-group $RESOURCE_GROUP \
          --overwrite-existing

    - name: Login to ACR
      run: az acr login --name $ACR_NAME

    - name: Build image
      run: docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .

    - name: Push image
      run: docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s-deployment.yaml
        kubectl apply -f k8s-service.yaml